#This playbbok will install HTTP server and will not start the server.

---
- hosts: appservers
  become: true
  tasks:
    - name: Install Apache HTTP server
      yum: name=httpd update_cache=yes state=latest
...
