- hosts: jenkinsserver
  become: yes
  tasks:
  - name: Download Long Term Jenkins release
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
  - name: Import jenkins key from url
    rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
  - name: Install java
    yum:
      name: java-21-openjdk
      state: present
  - name: Install EPEL Relaase which has daemonize  dependency which is required for Jenkins.
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      state: present
      disable_gpg_check: true
  - name: Install Jenkins SeServicerver
    yum:
      name: jenkins
      state: latest
      skip_broken: yes
  - name: Start Jenkins Service
    service:
      name: jenkins
      state: started
  - name: Enable Jenkins Service
    systemd:
     name: jenkins
     enabled: true
  - name: Sleep for 30 seconds and continue with play
    wait_for:
     delay: 30
     port: 8080
  - name: Get the init password for Jenkins
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    changed_when: false
    register: result
  - name: Print init password 
    debug:
     var: result.stdout
